Jurisdiction search
hackforla/ballotnav pull request #210
Opened 2020-10-21 02:04 UTC by lennessyy

2020-10-21 02:26 UTC, jafow requested changes
Looking good. Please remove the macosx files in example data folder as these are just cruft that finder adds

2020-10-21 16:53 UTC, jmensch1 commented
hi @lennessyy, yes please change that DISABLE_DB_MIGRATION_AUTO_RUN back to 'yes'. Also, looks like you deleted the example_data.zip file itself. We actually need that file to stay in the repo -- we just don't need it to be unzipped. Can you put it back in? Thanks much!

2020-10-21 16:56 UTC, lennessyy commented
yes I just realized that - I did that by accident and am now putting it back and adding a bit to the documentation on migrating schemas for the first time

2020-10-21 17:00 UTC, jmensch1 commented on backend/models/jurisdiction.js
> +    let result = await sequelize.query(`SELECT * FROM jurisdictions_from_lonlatstring('${lat} ${lon}');`);
Based on Drew's example I think you'll need to reverse the order of the string, i.e., `${lon} ${lat}`

2020-10-21 17:01 UTC, jmensch1 commented on backend/routes/public.js
> +router.get('/latlon', control.getJurisdictionsFromLatLon);
This should be `router.post` since we're passing the lon and lat in the body of the request.

2020-10-21 17:18 UTC, lennessyy commented on backend/routes/public.js
> +router.get('/latlon', control.getJurisdictionsFromLatLon);
fixed - was meaning to ask about this yesterday but forgot lol

2020-10-21 17:18 UTC, lennessyy commented on backend/models/jurisdiction.js
> +    let result = await sequelize.query(`SELECT * FROM jurisdictions_from_lonlatstring('${lat} ${lon}');`);
fixed

2020-10-21 17:49 UTC, jmensch1 approved these changes

2020-10-21 19:10 UTC, jafow commented on backend/models/jurisdiction.js
> +    let result = await sequelize.query(`SELECT * FROM jurisdictions_from_lonlatstring('${lon} ${lat}');`);
please wrap this in a try catch block because if the query fails -- for example if the lat long points are bad -- then i think we'll get an unhandled promise rejection error. 

we could just catch and then re-raise the exception here because the controller is catching

2020-10-21 19:15 UTC, jmensch1 commented on backend/models/jurisdiction.js
> +    let result = await sequelize.query(`SELECT * FROM jurisdictions_from_lonlatstring('${lon} ${lat}');`);
yeah good point. might even be better to move this logic into the controller itself (which is already handling the exception), since we generally haven't been decorating the models like this so it kinda breaks our pattern

2020-10-21 20:03 UTC, lennessyy commented on backend/models/jurisdiction.js
> +    let result = await sequelize.query(`SELECT * FROM jurisdictions_from_lonlatstring('${lon} ${lat}');`);
ah I have always thought if the controller is catching then the model doesn't need to catch. Good to know - I'll move this logic into the controller itself then

2020-10-22 16:50 UTC, jmensch1 approved these changes

2020-10-22 17:32 UTC, closed without merging