add example schema
hackforla/ballotnav pull request #32
Opened 2020-09-10 06:31 UTC by jafow

moving this from sheets simply because of syntax highlighting and visibility (sheets gets so cluttered so fast!)

2020-09-10 06:38 UTC, jafow commented on backend/db/schema.sql
> +    contact_name varchar(255),
`varchar(255)` is larger than necessary, but we should prefer simplicity and flexibility where we can, and try to be sane where know we can. 

for example it'd just be silly to store state abbreviations with varchar255!

2020-09-10 06:38 UTC, jafow commented on backend/db/schema.sql
> +    fax varchar(255),
I expect we'll have an easier time of it if we store phone & fax numbers as strings

2020-09-10 06:38 UTC, jafow commented on backend/db/schema.sql
> +    source_url varchar(255)
these 2 are unclear to me; or at least source_url is. 
I believe this s the data source where we got the information? 

I could see this being its own reference table

2020-09-10 06:38 UTC, jafow commented on backend/db/schema.sql
> +    latitude numeric,
added these because we will probably want at some poinit. -- up for debate is storing them separately or as a type `point` `(x, y)`. 

the postgres gis extension that foodoasis uses comes with a `geography` type that is kinda slick and tailor made for lat/long. won't add it until we need it though :-)

2020-09-10 22:27 UTC, theswerd commented on backend/db/schema.sql
> +    state_name varchar(20) NOT NULL,
This should be 
```suggestion
    state_name varchar(12) NOT NULL,
```

as the longest state name is **Rhode Island** with 12 characters

2020-09-10 22:31 UTC, theswerd requested changes
Please edit the state length -- then I will approve

2020-09-11 02:47 UTC, jafow commented on backend/db/schema.sql
> +    state_name varchar(20) NOT NULL,
North Carolina has 14, so does its neighbor to the south, South Carolina.
West Virginia has 13

don't sleep on the southern atlantic coast they are nice :-D

2020-09-11 02:49 UTC, jafow commented on backend/db/schema.sql
> +    state_name varchar(20) NOT NULL,
If California splits North California will have a whopping 16 chars!

i hope ballot nav lives a long time and we have know way of knowing what could happen, so why not spare some extra bytes :laughing:

2020-09-11 02:49 UTC, jafow commented on backend/db/schema.sql
> +    state_name varchar(20) NOT NULL,
Washington D.C. has 15!

2020-09-11 02:52 UTC, theswerd commented on backend/db/schema.sql
> +    state_name varchar(20) NOT NULL,
Hmm -- Google Search has failed me

2020-09-11 02:52 UTC, theswerd approved these changes

2020-09-11 02:54 UTC, merged